"""empty message

Revision ID: 64c19cc5124c
Revises: 962ddbc3429d
Create Date: 2016-04-29 23:24:13.396602

"""

# revision identifiers, used by Alembic.
revision = '64c19cc5124c'
down_revision = '962ddbc3429d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raboty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Imya_r', sa.String(length=60), nullable=True),
    sa.Column('Koeff', sa.Integer(), nullable=True),
    sa.Column('Proiz', sa.Integer(), nullable=True),
    sa.Column('Cena_r', sa.Numeric(precision=8.3), nullable=True),
    sa.Column('Ed_izm', sa.Numeric(precision=8.3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raboty_Cena_r'), 'raboty', ['Cena_r'], unique=False)
    op.create_index(op.f('ix_raboty_Ed_izm'), 'raboty', ['Ed_izm'], unique=False)
    op.create_index(op.f('ix_raboty_Imya_r'), 'raboty', ['Imya_r'], unique=False)
    op.create_index(op.f('ix_raboty_Koeff'), 'raboty', ['Koeff'], unique=False)
    op.create_index(op.f('ix_raboty_Proiz'), 'raboty', ['Proiz'], unique=False)
    op.add_column('izdeliya', sa.Column('rabota_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'izdeliya', 'raboty', ['rabota_id'], ['id'])
    op.add_column('zagotovki', sa.Column('Tip_proiz', sa.String(length=60), nullable=True))
    op.add_column('zagotovki', sa.Column('rabota_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_zagotovki_Tip_proiz'), 'zagotovki', ['Tip_proiz'], unique=False)
    op.create_foreign_key(None, 'zagotovki', 'raboty', ['rabota_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'zagotovki', type_='foreignkey')
    op.drop_index(op.f('ix_zagotovki_Tip_proiz'), table_name='zagotovki')
    op.drop_column('zagotovki', 'rabota_id')
    op.drop_column('zagotovki', 'Tip_proiz')
    op.drop_constraint(None, 'izdeliya', type_='foreignkey')
    op.drop_column('izdeliya', 'rabota_id')
    op.drop_index(op.f('ix_raboty_Proiz'), table_name='raboty')
    op.drop_index(op.f('ix_raboty_Koeff'), table_name='raboty')
    op.drop_index(op.f('ix_raboty_Imya_r'), table_name='raboty')
    op.drop_index(op.f('ix_raboty_Ed_izm'), table_name='raboty')
    op.drop_index(op.f('ix_raboty_Cena_r'), table_name='raboty')
    op.drop_table('raboty')
    ### end Alembic commands ###
