"""empty message

Revision ID: 962ddbc3429d
Revises: None
Create Date: 2016-04-27 21:26:57.380238

"""

# revision identifiers, used by Alembic.
revision = '962ddbc3429d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('izdeliya',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Imya_iz', sa.String(length=60), nullable=True),
    sa.Column('Kol_vo', sa.Integer(), nullable=True),
    sa.Column('Razmer_kubm', sa.Integer(), nullable=True),
    sa.Column('Cena_iz', sa.Numeric(precision=8.3), nullable=True),
    sa.Column('Chertez', sa.String(length=255), nullable=True),
    sa.Column('Eskiz', sa.String(length=255), nullable=True),
    sa.Column('Sert', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_izdeliya_Cena_iz'), 'izdeliya', ['Cena_iz'], unique=False)
    op.create_index(op.f('ix_izdeliya_Imya_iz'), 'izdeliya', ['Imya_iz'], unique=False)
    op.create_index(op.f('ix_izdeliya_Kol_vo'), 'izdeliya', ['Kol_vo'], unique=False)
    op.create_index(op.f('ix_izdeliya_Razmer_kubm'), 'izdeliya', ['Razmer_kubm'], unique=False)
    op.create_table('klienty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FIO', sa.String(length=120), nullable=True),
    sa.Column('Vozrast', sa.Integer(), nullable=True),
    sa.Column('Adres', sa.String(length=64), nullable=True),
    sa.Column('Email', sa.String(length=120), nullable=True),
    sa.Column('Telefon', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_klienty_Adres'), 'klienty', ['Adres'], unique=True)
    op.create_index(op.f('ix_klienty_Email'), 'klienty', ['Email'], unique=True)
    op.create_index(op.f('ix_klienty_FIO'), 'klienty', ['FIO'], unique=True)
    op.create_index(op.f('ix_klienty_Telefon'), 'klienty', ['Telefon'], unique=False)
    op.create_index(op.f('ix_klienty_Vozrast'), 'klienty', ['Vozrast'], unique=False)
    op.create_table('postavschiki',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Imya', sa.String(length=60), nullable=True),
    sa.Column('Telefon', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postavschiki_Imya'), 'postavschiki', ['Imya'], unique=False)
    op.create_index(op.f('ix_postavschiki_Telefon'), 'postavschiki', ['Telefon'], unique=False)
    op.create_table('roly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Imya', sa.String(length=64), nullable=True),
    sa.Column('access_level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Imya')
    )
    op.create_table('postavki',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Postavschik', sa.String(length=60), nullable=True),
    sa.Column('Material', sa.String(length=60), nullable=True),
    sa.Column('Cena_dost', sa.Numeric(precision=8.3), nullable=True),
    sa.Column('Data', sa.Date(), nullable=True),
    sa.Column('Kol_vo', sa.Integer(), nullable=True),
    sa.Column('postavschik_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['postavschik_id'], ['postavschiki.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postavki_Cena_dost'), 'postavki', ['Cena_dost'], unique=False)
    op.create_index(op.f('ix_postavki_Data'), 'postavki', ['Data'], unique=False)
    op.create_index(op.f('ix_postavki_Kol_vo'), 'postavki', ['Kol_vo'], unique=False)
    op.create_index(op.f('ix_postavki_Material'), 'postavki', ['Material'], unique=False)
    op.create_index(op.f('ix_postavki_Postavschik'), 'postavki', ['Postavschik'], unique=False)
    op.create_table('sotrudniki',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FIO', sa.String(length=120), nullable=True),
    sa.Column('Dolznost', sa.String(length=64), nullable=True),
    sa.Column('Vozrast', sa.Integer(), nullable=True),
    sa.Column('Telefon', sa.String(length=20), nullable=True),
    sa.Column('Otdel', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=120), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['roly.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sotrudniki_Dolznost'), 'sotrudniki', ['Dolznost'], unique=True)
    op.create_index(op.f('ix_sotrudniki_FIO'), 'sotrudniki', ['FIO'], unique=True)
    op.create_index(op.f('ix_sotrudniki_Otdel'), 'sotrudniki', ['Otdel'], unique=False)
    op.create_index(op.f('ix_sotrudniki_Telefon'), 'sotrudniki', ['Telefon'], unique=False)
    op.create_index(op.f('ix_sotrudniki_Vozrast'), 'sotrudniki', ['Vozrast'], unique=False)
    op.create_index(op.f('ix_sotrudniki_email'), 'sotrudniki', ['email'], unique=True)
    op.create_table('materialy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Imya_m', sa.String(length=60), nullable=True),
    sa.Column('Kol_vo', sa.Integer(), nullable=True),
    sa.Column('Cena_m', sa.Numeric(precision=8.3), nullable=True),
    sa.Column('postavka_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['postavka_id'], ['postavki.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materialy_Cena_m'), 'materialy', ['Cena_m'], unique=False)
    op.create_index(op.f('ix_materialy_Imya_m'), 'materialy', ['Imya_m'], unique=False)
    op.create_index(op.f('ix_materialy_Kol_vo'), 'materialy', ['Kol_vo'], unique=False)
    op.create_table('zayavki',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FIO_sotr', sa.String(length=120), nullable=True),
    sa.Column('FIO_kl', sa.String(length=120), nullable=True),
    sa.Column('Nazv_izd', sa.String(length=60), nullable=True),
    sa.Column('Data', sa.Date(), nullable=True),
    sa.Column('Avans', sa.Numeric(precision=8.3), nullable=True),
    sa.Column('klient_id', sa.Integer(), nullable=True),
    sa.Column('sotrudnik_id', sa.Integer(), nullable=True),
    sa.Column('izdelie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['izdelie_id'], ['izdeliya.id'], ),
    sa.ForeignKeyConstraint(['klient_id'], ['klienty.id'], ),
    sa.ForeignKeyConstraint(['sotrudnik_id'], ['sotrudniki.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zayavki_Avans'), 'zayavki', ['Avans'], unique=False)
    op.create_index(op.f('ix_zayavki_Data'), 'zayavki', ['Data'], unique=False)
    op.create_index(op.f('ix_zayavki_FIO_kl'), 'zayavki', ['FIO_kl'], unique=True)
    op.create_index(op.f('ix_zayavki_FIO_sotr'), 'zayavki', ['FIO_sotr'], unique=True)
    op.create_index(op.f('ix_zayavki_Nazv_izd'), 'zayavki', ['Nazv_izd'], unique=False)
    op.create_table('sostav_m',
    sa.Column('izdelie_id', sa.Integer(), nullable=True),
    sa.Column('aterial_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aterial_id'], ['materialy.id'], ),
    sa.ForeignKeyConstraint(['izdelie_id'], ['izdeliya.id'], )
    )
    op.create_table('zagotovki',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Imya_z', sa.String(length=60), nullable=True),
    sa.Column('Kol_vo', sa.Integer(), nullable=True),
    sa.Column('Dlina', sa.Integer(), nullable=True),
    sa.Column('Shirina', sa.Integer(), nullable=True),
    sa.Column('Vysota', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materialy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zagotovki_Dlina'), 'zagotovki', ['Dlina'], unique=False)
    op.create_index(op.f('ix_zagotovki_Imya_z'), 'zagotovki', ['Imya_z'], unique=False)
    op.create_index(op.f('ix_zagotovki_Kol_vo'), 'zagotovki', ['Kol_vo'], unique=False)
    op.create_index(op.f('ix_zagotovki_Shirina'), 'zagotovki', ['Shirina'], unique=False)
    op.create_index(op.f('ix_zagotovki_Vysota'), 'zagotovki', ['Vysota'], unique=False)
    op.create_table('sostav_z',
    sa.Column('izdelie_id', sa.Integer(), nullable=True),
    sa.Column('polufabricat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['izdelie_id'], ['izdeliya.id'], ),
    sa.ForeignKeyConstraint(['polufabricat_id'], ['zagotovki.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sostav_z')
    op.drop_index(op.f('ix_zagotovki_Vysota'), table_name='zagotovki')
    op.drop_index(op.f('ix_zagotovki_Shirina'), table_name='zagotovki')
    op.drop_index(op.f('ix_zagotovki_Kol_vo'), table_name='zagotovki')
    op.drop_index(op.f('ix_zagotovki_Imya_z'), table_name='zagotovki')
    op.drop_index(op.f('ix_zagotovki_Dlina'), table_name='zagotovki')
    op.drop_table('zagotovki')
    op.drop_table('sostav_m')
    op.drop_index(op.f('ix_zayavki_Nazv_izd'), table_name='zayavki')
    op.drop_index(op.f('ix_zayavki_FIO_sotr'), table_name='zayavki')
    op.drop_index(op.f('ix_zayavki_FIO_kl'), table_name='zayavki')
    op.drop_index(op.f('ix_zayavki_Data'), table_name='zayavki')
    op.drop_index(op.f('ix_zayavki_Avans'), table_name='zayavki')
    op.drop_table('zayavki')
    op.drop_index(op.f('ix_materialy_Kol_vo'), table_name='materialy')
    op.drop_index(op.f('ix_materialy_Imya_m'), table_name='materialy')
    op.drop_index(op.f('ix_materialy_Cena_m'), table_name='materialy')
    op.drop_table('materialy')
    op.drop_index(op.f('ix_sotrudniki_email'), table_name='sotrudniki')
    op.drop_index(op.f('ix_sotrudniki_Vozrast'), table_name='sotrudniki')
    op.drop_index(op.f('ix_sotrudniki_Telefon'), table_name='sotrudniki')
    op.drop_index(op.f('ix_sotrudniki_Otdel'), table_name='sotrudniki')
    op.drop_index(op.f('ix_sotrudniki_FIO'), table_name='sotrudniki')
    op.drop_index(op.f('ix_sotrudniki_Dolznost'), table_name='sotrudniki')
    op.drop_table('sotrudniki')
    op.drop_index(op.f('ix_postavki_Postavschik'), table_name='postavki')
    op.drop_index(op.f('ix_postavki_Material'), table_name='postavki')
    op.drop_index(op.f('ix_postavki_Kol_vo'), table_name='postavki')
    op.drop_index(op.f('ix_postavki_Data'), table_name='postavki')
    op.drop_index(op.f('ix_postavki_Cena_dost'), table_name='postavki')
    op.drop_table('postavki')
    op.drop_table('roly')
    op.drop_index(op.f('ix_postavschiki_Telefon'), table_name='postavschiki')
    op.drop_index(op.f('ix_postavschiki_Imya'), table_name='postavschiki')
    op.drop_table('postavschiki')
    op.drop_index(op.f('ix_klienty_Vozrast'), table_name='klienty')
    op.drop_index(op.f('ix_klienty_Telefon'), table_name='klienty')
    op.drop_index(op.f('ix_klienty_FIO'), table_name='klienty')
    op.drop_index(op.f('ix_klienty_Email'), table_name='klienty')
    op.drop_index(op.f('ix_klienty_Adres'), table_name='klienty')
    op.drop_table('klienty')
    op.drop_index(op.f('ix_izdeliya_Razmer_kubm'), table_name='izdeliya')
    op.drop_index(op.f('ix_izdeliya_Kol_vo'), table_name='izdeliya')
    op.drop_index(op.f('ix_izdeliya_Imya_iz'), table_name='izdeliya')
    op.drop_index(op.f('ix_izdeliya_Cena_iz'), table_name='izdeliya')
    op.drop_table('izdeliya')
    ### end Alembic commands ###
